name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Repoyu Çek
      uses: actions/checkout@v4

    - name: Python Kurulumu
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Java JDK 17 Kurulumu
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Sistem Sistem Bağımlılıklarını ve Buildozer'ı Kur
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libgdbm-dev libncurses5-dev libssl-dev libffi-dev libreadline-dev libsqlite3-dev libbz2-dev ccache zip unzip
        python -m pip install --upgrade pip setuptools
        pip install "cython<3.0.0" buildozer

    - name: APK Derleme (Buildozer)
      run: |
        buildozer -v android debug

    - name: APK Dosyasını Yükle
      uses: actions/upload-artifact@v4
      with:
        name: CifcilerHesaplayici-APK
        path: bin/*.apk
